spring:
  application:
    name: Customer Service  # Unique service name

server:
  port: 8081  # Customer service will run on this port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of Eureka Server
  instance:
    prefer-ip-address: true  # Uses IP address instead of hostname
