spring:
  application:
    name: Eureka Server  # Unique service name

server:
  port: 8761  # Default Eureka Server port

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Eureka server does not register itself
    fetch-registry: false  # Server does not need to fetch other services
